# Apprendimento supervisionato

Questa esercitazione, basata sullo stesso dataset della precedente, è finalizzato a comprendere quali siano le principali funzioni e metodi connessi all'ambito di tre task di apprendimento supervisionato:

1. Classificazione binaria su `death`;

2. Classificazione multiclasse su `dzgroup`;

3. Regressione su `aps`.

In [100]:
import numpy as np
import pandas as pd
from sklearn._config import set_config

set_config(transform_output = 'pandas')

In [101]:
dd = pd.read_csv('data/dataset_esercitazione.csv')
dd

,age,sex,dzgroup,dzclass,num.co,edu,income,scoma,charges,totcst,...,crea,sod,ph,glucose,bun,urine,adlp,adls,adlsc,death
0,62.84998,male,Lung Cancer,Cancer,0,11.0,$11-$25k,0.0,9715.0,NaN,...,1.199951,141.0,7.459961,NaN,NaN,NaN,7.0,7.0,7.000000,0
1,60.33899,female,Cirrhosis,COPD/CHF/Cirrhosis,2,12.0,$11-$25k,44.0,34496.0,NaN,...,5.500000,132.0,7.250000,NaN,NaN,NaN,NaN,1.0,1.000000,1
2,52.74698,female,Cirrhosis,COPD/CHF/Cirrhosis,2,12.0,under $11k,0.0,41094.0,NaN,...,2.000000,134.0,7.459961,NaN,NaN,NaN,1.0,0.0,0.000000,1
3,42.38498,female,Lung Cancer,Cancer,2,11.0,under $11k,0.0,3075.0,NaN,...,0.799927,139.0,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,1
4,79.88495,female,ARF/MOSF w/Sepsis,ARF/MOSF,1,NaN,NaN,26.0,50127.0,NaN,...,0.799927,143.0,7.509766,NaN,NaN,NaN,NaN,2.0,2.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9100,66.07300,male,ARF/MOSF w/Sepsis,ARF/MOSF,1,8.0,NaN,0.0,52870.0,34329.3125,...,1.099854,131.0,7.459961,188.0,21.0,NaN,NaN,0.0,0.000000,0
9101,55.15399,female,Coma,Coma,1,11.0,NaN,41.0,35377.0,23558.5000,...,5.899414,135.0,7.289062,190.0,49.0,0.0,NaN,0.0,0.000000,0
9102,70.38196,male,ARF/MOSF w/Sepsis,ARF/MOSF,1,NaN,NaN,0.0,46564.0,31409.0156,...,2.699707,139.0,7.379883,189.0,60.0,3900.0,NaN,NaN,2.525391,0
9103,47.01999,male,MOSF w/Malig,ARF/MOSF,1,13.0,NaN,0.0,58439.0,NaN,...,3.500000,135.0,7.469727,246.0,55.0,NaN,NaN,0.0,0.000000,1
9104,81.53894,female,ARF/MOSF w/Sepsis,ARF/MOSF,1,8.0,$11-$25k,0.0,15604.0,10605.7578,...,1.199951,137.0,7.289062,187.0,15.0,NaN,0.0,NaN,0.494751,1

In [102]:
dd.describe()

,age,num.co,edu,scoma,charges,totcst,totmcst,avtisst,sps,aps,...,crea,sod,ph,glucose,bun,urine,adlp,adls,adlsc,death
count,9105.000000,9105.000000,7471.000000,9104.000000,8.933000e+03,8217.000000,5630.000000,9023.000000,9104.000000,9104.000000,...,9038.000000,9104.000000,6821.000000,4605.000000,4753.000000,4243.000000,3464.000000,6238.000000,9105.000000,9105.000000
mean,62.650823,1.868644,11.747691,12.058546,5.999579e+04,30825.867768,28828.877838,22.610928,25.525872,37.597979,...,1.770961,137.568541,7.415364,159.873398,32.349463,2191.546047,1.157910,1.637384,1.888272,0.681054
std,15.593710,1.344409,3.447743,24.636694,1.026488e+05,45780.820986,43604.261932,13.233248,9.899377,19.903852,...,1.686041,6.029326,0.080563,88.391541,26.792288,1455.245777,1.739672,2.231358,2.003763,0.466094
min,18.041990,0.000000,0.000000,0.000000,1.169000e+03,0.000000,-102.719970,1.000000,0.199982,0.000000,...,0.099991,110.000000,6.829102,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,52.797000,1.000000,10.000000,0.000000,9.740000e+03,5929.566400,5177.404300,12.000000,19.000000,23.000000,...,0.899902,134.000000,7.379883,103.000000,14.000000,1165.500000,0.000000,0.000000,0.000000,0.000000
50%,64.856990,2.000000,12.000000,0.000000,2.502400e+04,14452.734400,13223.500000,19.500000,23.898438,34.000000,...,1.199951,137.000000,7.419922,135.000000,23.000000,1968.000000,0.000000,1.000000,1.000000,1.000000
75%,73.998960,3.000000,14.000000,9.000000,6.459800e+04,36087.937500,34223.601600,31.666656,30.199219,49.000000,...,1.899902,141.000000,7.469727,188.000000,42.000000,3000.000000,2.000000,3.000000,3.000000,1.000000
max,101.847960,9.000000,31.000000,100.000000,1.435423e+06,633212.000000,710682.000000,83.000000,99.187500,143.000000,...,21.500000,181.000000,7.769531,1092.000000,300.000000,9000.000000,7.000000,7.000000,7.073242,1.000000

In [103]:
dd.isna().mean().sort_values(ascending = False) # rimuovo adlp e urine

adlp        0.619550
urine       0.533992
glucose     0.494234
bun         0.477979
totmcst     0.381658
alb         0.370346
income      0.327512
adls        0.314882
bili        0.285667
pafi        0.255354
ph          0.250851
prg2m       0.181109
edu         0.179462
prg6m       0.179352
totcst      0.097529
wblc        0.023284
charges     0.018891
avtisst     0.009006
crea        0.007359
race        0.004613
dnr         0.003295
dnrday      0.003295
sps         0.000110
surv2m      0.000110
scoma       0.000110
resp        0.000110
temp        0.000110
sod         0.000110
hrt         0.000110
meanbp      0.000110
aps         0.000110
surv6m      0.000110
age         0.000000
sex         0.000000
dzgroup     0.000000
num.co      0.000000
dzclass     0.000000
hday        0.000000
diabetes    0.000000
ca          0.000000
dementia    0.000000
adlsc       0.000000
death       0.000000
dtype: float64

In [104]:
dd.shape

(9105, 43)

In [105]:
# drop sparse
ft_to_drop = ['adlp', 'urine']

dd = dd.drop(columns = ft_to_drop)
dd.shape

(9105, 41)

## Classificazione binaria

Da questo momento il codice si frammenta e si eseguiranno i tre codici separatamente. In questa esercitazione porremo focus sulla variabile target `death` che rappresenta un outcome binario:
- 0 vivo;
- 1 morto

Per evitare data leakage informativo rimuoviamo le feature prognostiche che possono dare indicazioni di come un'osservazione debba essere classificata.
 - `aps`, `sps` score clinici;
 - `dzgroup`, `dzclass` gruppi diagnostici;

In [106]:
diag_to_drop = ['aps', 'sps', 'dzgroup', 'dzclass']
dd = dd.drop(columns = diag_to_drop)
dd.shape

(9105, 37)

Come nell'esempio precedente, rimuoviamo le variabili prognostiche esistenti e, dopo aver effettuato lo splitting, eseguiamo tutto il pre-processing necessario : rimozioni sparse -> imputazione -> encoding -> standardizzazione -> analisi correlazione (2 step) -> feature selection.

1. Procedere allo split train-test secondo il rapporto 95%-5% in forma stratificata secondo i valori della variabile target.

In [107]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, StandardScaler

In [108]:
X = dd.drop(columns = ['death'])
y = dd['death']

In [109]:
X_tr, X_te, y_tr, y_te = train_test_split(X, 
                                          y, 
                                          test_size = 0.05, 
                                          stratify = y, 
                                          random_state = 42)

In [110]:
imp_num = SimpleImputer(strategy='median')
imp_cat = SimpleImputer(strategy='constant', fill_value='missing')

In [111]:
num_cols = X_tr.select_dtypes(include = 'number').columns
num_cols

Index(['age', 'num.co', 'edu', 'scoma', 'charges', 'totcst', 'totmcst',
       'avtisst', 'surv2m', 'surv6m', 'hday', 'diabetes', 'dementia', 'prg2m',
       'prg6m', 'dnrday', 'meanbp', 'wblc', 'hrt', 'resp', 'temp', 'pafi',
       'alb', 'bili', 'crea', 'sod', 'ph', 'glucose', 'bun', 'adls', 'adlsc'],
      dtype='object')

In [112]:
cat_cols = X_tr.select_dtypes(exclude = 'number').columns
cat_cols

Index(['sex', 'income', 'race', 'ca', 'dnr'], dtype='object')

In [113]:
X_tr[cat_cols].apply(lambda x: x.unique())

sex                                       [female, male]
income      [nan, under $11k, $25-$50k, $11-$25k, >$50k]
race         [white, black, hispanic, nan, other, asian]
ca                                 [no, metastatic, yes]
dnr       [no dnr, dnr after sadm, dnr before sadm, nan]
dtype: object

In [114]:
ord_cols = ['income', 'ca']

In [115]:
# Imputazione
X_tr[num_cols] = imp_num.fit_transform(X_tr[num_cols])
X_tr[cat_cols] = imp_cat.fit_transform(X_tr[cat_cols])


X_te[num_cols] = imp_num.transform(X_te[num_cols])
X_te[cat_cols] = imp_cat.transform(X_te[cat_cols])

In [116]:
X_tr.isna().mean().sort_values(ascending = False)

age         0.0
sex         0.0
num.co      0.0
edu         0.0
income      0.0
scoma       0.0
charges     0.0
totcst      0.0
totmcst     0.0
avtisst     0.0
race        0.0
surv2m      0.0
surv6m      0.0
hday        0.0
diabetes    0.0
dementia    0.0
ca          0.0
prg2m       0.0
prg6m       0.0
dnr         0.0
dnrday      0.0
meanbp      0.0
wblc        0.0
hrt         0.0
resp        0.0
temp        0.0
pafi        0.0
alb         0.0
bili        0.0
crea        0.0
sod         0.0
ph          0.0
glucose     0.0
bun         0.0
adls        0.0
adlsc       0.0
dtype: float64

In [117]:
X_te.isna().mean().sort_values(ascending = False)

age         0.0
sex         0.0
num.co      0.0
edu         0.0
income      0.0
scoma       0.0
charges     0.0
totcst      0.0
totmcst     0.0
avtisst     0.0
race        0.0
surv2m      0.0
surv6m      0.0
hday        0.0
diabetes    0.0
dementia    0.0
ca          0.0
prg2m       0.0
prg6m       0.0
dnr         0.0
dnrday      0.0
meanbp      0.0
wblc        0.0
hrt         0.0
resp        0.0
temp        0.0
pafi        0.0
alb         0.0
bili        0.0
crea        0.0
sod         0.0
ph          0.0
glucose     0.0
bun         0.0
adls        0.0
adlsc       0.0
dtype: float64

Sono stati imputati correttamente i dati mancanti. Si procede con l'ordinal encoding.

In [118]:
ord_mods = [['missing', 'under $11k', '$11-$25k', '$25-$50k', '>$50k'], ['missing', 'no', 'yes', 'metastatic']]

enc1 = OrdinalEncoder()
enc2 = OrdinalEncoder(categories = ord_mods)

In [119]:
new_cat_cols = cat_cols.drop(ord_cols)
X_tr[new_cat_cols] = enc1.fit_transform(X_tr[new_cat_cols])
X_tr[ord_cols] = enc2.fit_transform(X_tr[ord_cols])

X_te[new_cat_cols] = enc1.transform(X_te[new_cat_cols])
X_te[ord_cols] = enc2.transform(X_te[ord_cols])

In [120]:
sc = StandardScaler()

X_tr = sc.fit_transform(X_tr)
X_te = sc.transform(X_te)

In questo caso, a differenza del precedente, in cui veniva richiesto il clustering, adesso è necessario valutare anche la correlazione tra la risposta e le features, rimuovendo quelle che assumono valori troppo bassi e suggeriscono di non essere rulevanti per prevedere i valori di y.

In [121]:
soglia = 0.1

col_to_remove = (
    X_tr.corrwith(y_tr)
    .abs()
    .sort_values(ascending = False)
    .loc[lambda x: x < soglia]
    .index
)

len(col_to_remove) # 25 features poco correlate con il target

25

In [122]:
X_tr = X_tr.drop(columns = col_to_remove)
X_te = X_te.drop(columns = col_to_remove)

In [123]:
soglia = 0.8
coppie = (
    X_tr.corr()
    .abs()
    .map(lambda x: x > soglia)
    .unstack()
    .reset_index()
)

coppie.columns = ['var1', 'var2', 'high_corr']

(coppie 
 .loc[lambda x: (x['high_corr'] == True) & (x['var1'] < x['var2']),
      ['var1', 'var2']
      ])

      var1    var2
37  surv2m  surv6m
73   prg2m   prg6m

In [124]:
X_tr['survmean'] = X_tr[['surv2m', 'surv6m']].mean(axis = 1)
X_te['survmean'] = X_te[['surv2m', 'surv6m']].mean(axis = 1)

X_tr['prgmean'] = X_tr[['prg2m', 'prg6m']].mean(axis = 1)
X_te['prgmean'] = X_te[['prg2m', 'prg6m']].mean(axis = 1)

In [125]:
X_tr = X_tr.drop(columns = ['surv2m', 'surv6m', 'prg2m', 'prg6m'])
X_te = X_te.drop(columns = ['surv2m', 'surv6m', 'prg2m', 'prg6m'])

In [126]:
X_tr.shape

(8649, 9)

In [127]:
X_te.shape

(456, 9)

È stata calcolata una variabile sintetica combinazione lineare delle variabili multicollineari, data dalla **media per riga delle feature interessate**; successivamente sono state rimosse quelle originali.

In [128]:
from sklearn.feature_selection import SelectKBest, f_classif
fs = SelectKBest(score_func=f_classif, k = "all").fit(X_tr, y_tr)
fs.pvalues_

array([6.88682686e-062, 3.72775851e-036, 3.55054397e-027, 1.19787885e-130,
       1.25429168e-291, 9.85209325e-045, 4.11933110e-049, 1.93636383e-252,
       1.12255860e-202])

In [ ]:
skb = SelectKBest(score_func = f_classif, k = 4)
X_tr_skb = skb.fit_transform(X_tr, y_tr)
X_te_skb = skb.transform(X_te)

In [131]:
X_tr_skb.columns.to_list()

['ca', 'dnr', 'survmean', 'prgmean']

## Classificatore binario

### RandomForestClassifier / LogisticRegression / SVC / AdaBoost